### PR TITLE
Add support for client-side javascript

### PR DESCRIPTION
**Pull request by gjvis**
Compilation is done with browserify, transpilation is done with babel, minification is done with uglify.

This is a precursor to having a progressively-enhanced datepicker on the "add job application" screen

### CODE REVIEW

**Comment by lukasz-kaniowski** [comment]
`npm run watch` dies if there is parsing error in `assets/main.js` with error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token
[1]    84031 segmentation fault  npm run watch
```
It maybe enough to add `.pipe(plumber())` to `browserify` gulp task

**Comment by gjvis** [comment]
Gah, I tried so many combinations of processors and managed to lose plumber somehow! Sorting now

**Comment by gjvis** [comment]
Ok, I think that this is good to go

**Comment by lukasz-kaniowski** [comment]
:shipit:

**Pull request merged**
