### PR TITLE
Addition of Updated date to dashboard

### PR DESCRIPTION
**Pull request by nathancashmoredwp**
OR-90 first draft for review by @jessstubenbord

### CODE REVIEW

**Comment by lukasz-kaniowski** [comment]
👍

**Comment by jessstubenbord** [comment]
can we scale the font sizes on the dates down to 16px?

**Comment by jessstubenbord** [comment]
@nathancashmoredwp otherwise, it looks great

**Comment by nathancashmoredwp** [comment]
🚀

**Pull request merged**
