### PR TITLE
Add integration test for add a job page

### PR DESCRIPTION
**Pull request by lukasz-kaniowski**

### CODE REVIEW

**Comment by gjvis** [comment]
👍

**Comment by lukasz-kaniowski** [comment]
@gjvis what is your opinion about moving PageObjects to common test directory as they are currently used by mocha and cucumber

**Comment by gjvis** [comment]
I think that's a good idea

**Comment by lukasz-kaniowski** [comment]
I think to have it like that
```
test/
  features/
  integration/
  common/
     PageObject.js
```
I will get rid of `sampleSpec.js` and `specHelper.js`

**Comment by gjvis** [comment]
I'm not a huge fan of moving "features" under test (as they're not tests), but its probably simpler for now.

The structure of the whole repo needs rethinking, the root is quite noisy at the moment.

**Comment by gjvis** [comment]
in case it wasn't clear, that was a 👍 to you proposed directory structure!

**Comment by lukasz-kaniowski** [comment]
have a look now

**Comment by gjvis** [comment]
looks good

**Comment by gjvis** [comment]
🚢

**Pull request merged**
